### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by imay** [arangodb/velocypack#136]
There will be almost 1 year since the latest release, many issues have been fixed during this period.
I'm wondering if there is a plan of new release.
Looking forward to the new release, then we don't need to a private patch.

**Comment by jsteemann** [comment]
Hi @imay,
actually we normally don't tag and build proper releases of velocypack.
In our other projects, we include it as a git submodule, and from time to time pin the submodule to the newest version in the `main` branch of the velocypack repository. That has worked fine for us.
If it helps you, I can also tag the current version of main. Please let me know if I should do this.

**Comment by imay** [comment]
Thanks  @jsteemann 
It will help us very much if you can provide a tag. Because our project don't leverage git submodule and we use the release version of this project. So a tag will really help us.

**Comment by jsteemann** [comment]
Hi @imay,
just created tag `v0.2.0` with the current state of `main`.

**Comment by imay** [comment]
Great! Thank you @jsteemann ! very appreciate!
