### ISSUE TITLE
Builder.cpp set(ValuePair) memleak?

### ISSUE THREAD

**Issue by baslr** [arangodb/velocypack#14]
```cpp
  if (pair.valueType() == ValueType::Binary) {
    uint64_t v = pair.getSize();
    appendUInt(v, 0xbf);
    memcpy(_start + _pos, pair.getStart(), checkOverflow(v));
    _pos += v;
    return _start + oldPos;
  }
```
https://github.com/arangodb/velocypack/blob/4467c7341ca9375e41c7d1e0065af8002d49b6f7/src/Builder.cpp#L703

Where did the memory come from? Since no reserveSpace is called or did I miss something?

**Comment by neunhoef** [comment]
This is a bug as far as I see. You are right. There is a reserveSpace missing. So this is a buffer overrun. I will fix this right away.

**Comment by neunhoef** [comment]
Thanks for the bug report, this is much appreciated.
