### ISSUE TITLE
Should values be store in their most compact representation?

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/velocypack#17]
Assume we have an array of int4, should each member of array store in their most compact representation?( here int1 or int2 or int4) then we have an array with index table(0x06).
or each int4 member can store in their original format? then we could store it in an array(0x02) without index table because they have same type.

should this be transparent to users or be decided by them?

**Comment by jsteemann** [comment]
VelocyPack does not distinguish between int1, int2 and int4. Instead it has the types Int and UInt. These types have a variable length encoding, so they can be used for all types of integers up to 64 bit precision. The SmallInt type offered by VelocyPack is just an optimization, and it will be used automatically when small enough values are added to a `Builder`.

VelocyPack is optimized for sequentially building values with a `Builder` object. The assumption here is that the user wants to put together values as easy as possible and does not care much about how the values are encoded internally in VelocyPack. And from the user perspective it should not make much difference if an Array or Object type with index or one without index is used.

But it may matter in terms of storage space. If this is your concern, then I suggest allowing the user to make the decision. AFAIR in the C++ version of the `Builder`, we always choose the index table version for types Array and Object unless some options are set in the `Options` object. The attributes that control the behavior are named `buildUnindexedArrays` and `buildUnindexedObjects` in the C++ version. They both default to `false`. But with the `Options` object that control a `Builder`s behavior, developers have control whether they prefer the compact or indexed format.

**Comment by ra0o0f** [comment]
@jsteemann thanks for the detailed response. currently C# encodes integral types equal to their declared type, not the length they can fit in.

For example one could use `Builder` to store number `15` declared as Int32 in C#(`Int32 a = 15`). currently it's encoded as `0x23` which requires 4Bytes space(same as its C# declared type). But since `15` is small enough it can be stored as `0x20`. My question was should I encode integral types to the least length for vpack `Int` they can fit in? 

I have already added a method that store integral types as the most compact representation, please take a look:
https://github.com/ra0o0f/velocypack.net/blob/master/src/ArangoDB.VelocyPack/VPackBuilder.cs#L109-L134

**Comment by jsteemann** [comment]
If you want to restore the original C# value type when unpacking a VelocyPack value, then you should use as much space as the C# type originally used, e.g. encode int32 using 4 bytes, int16 using 2 bytes etc. Then the convention would be to decode 4 byte integers into int32, 2 byte integers into int16 etc. This will waste some space however.
If you instead use the smallest possible VelocyPack type a number fits in, then you will save some space, but there is no way to tell the original C# number type from the VelocyPack value.

So the answer is: it depends on what your goals are. If you want users to decide whether they want most compact representation or preserve the original types, maybe making this option will help.

**Comment by ra0o0f** [comment]
Thanks @jsteemann for the great help, also `Slice` object can now retrieve value corresponding to VPack type or convert it to C# type that user wants.

I also asked this to know that compactness and saving space is the primary goal for the VPack creators and what would be the trade offs for that.

For making .NET implementation better any comment or advice would be a great help if you look at it.
