### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by yojimbo87** [arangodb/velocypack#19]
I wasn't able to build VPack library on Windows with current instructions given in `Install.md` file. Problem seems to be related to `build` subdirectory. Navigating there according to instructions and executing command:

```
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release
```

returns following error:

```
CMake Error: The source directory "D:/Programming/Projects/velocypack/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

Moving `CMakeLists.txt` file from root folder to `build` subdirectory and executing command again returns:

```
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build mode: Release
-- Install base directory: C:/Program Files/velocypack
CMake Error at CMakeLists.txt:37 (include):
  include could not find load file:

    AR_CompilerSettings


CMake Error at CMakeLists.txt:85 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.


CMake Error at CMakeLists.txt:86 (add_subdirectory):
  add_subdirectory given source "examples" which is not an existing
  directory.


CMake Error at CMakeLists.txt:87 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.


-- Configuring incomplete, errors occurred!
See also "D:/Programming/Projects/velocypack/build/CMakeFiles/CMakeOutput.log".
```

However if I execute the command from root folder of the repository then the build seems to be ok:

```
-- Build mode: Release
-- Install base directory: C:/Program Files/velocypack
-- Hardware support for SSE4.2 on this machine:
-- Compiler type MSVC: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Building with SSE 4.2 optimizations enabled: ON
-- Building bench performance test suite: OFF
-- Building support programs and tools: ON
-- Building examples: ON
-- Building test suite: OFF
-- Building large tests: OFF
-- Building assembler test suite: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Programming/Projects/velocypack
```

Resulting Visual Studio files are not generated in the `build` subdirectory location as stated in `Install.md` file, but in the root folder of the repository.

**Comment by dothebart** [comment]
hm, I guess the md is wrong there - its missing an information.

You need to specify the relative location of the source to your build directory:

    cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..

**Comment by jsteemann** [comment]
I think the build command in `Install.md` is correct. 
I also think that the problem is caused by the two missing `.` symbols at the end of the command you posted. They are relevant for cmake for picking up the correct `CMakeLists.txt` file:
`cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..`
Can you try adding the dots at the end of the command?

**Comment by yojimbo87** [comment]
You're right, my bad, command with two dots in the end works according to the instructions.
