### ISSUE TITLE
create new edge issue

### ISSUE THREAD

**Issue by wanghaiwin** [arangodb/velocypack#21]
Dear friends,

i am trying to import edges from csv. Below is the code：

final BaseEdgeDocument value;

value = new BaseEdgeDocument();

value.setKey(c15.getContents()+""+c13.getContents()+""+c4.getContents());
value.setFrom(c1.getContents());
value.setTo(c6.getContents());
value.addAttribute("start_station",c11.getContents());
value.addAttribute("end_station",c12.getContents());

try {
db.graph(GRAPH_NAME).edgeCollection(EDGE_COLLECTION_NAME).insertEdge(value);
System.out.println("Edge-document created"+value.toString());
} catch (final ArangoDBException e) {
System.err.println("Failed to create edge-document. " + e.getMessage());
}

the errors logs：
Failed to create edge-document. Response: 410, Error: 1906 - illegal document handle

i am looking for help.

best wishes.

**Comment by jsteemann** [comment]
The issue looks like it would fit into the [java driver repository](https://github.com/arangodb/arangodb-java-driver).
However, when looking at the above code, the error may happen when the contents of `c1` or `c6` do not contain a valid edge id. A valid edge id must consist of a valid collection name, then a forward slash plus a valid document key. Example: `users/abc`, `foo/bar` etc.
If `c1` or `c6` have any other contents then the error will occur intentionally.

@mpv1989

**Comment by dothebart** [comment]
Continuing discussion on https://github.com/arangodb/arangodb/issues/2679 - closing.
