### ISSUE TITLE
Other implementations?

### ISSUE THREAD

**Issue by FGasper** [arangodb/velocypack#26]
Are there vpack implementations in languages besides C++?

I’d be particularly curious about JavaScript for browser use. Server-side languages can bind to the C++, but JS needs a ground-up implementation.

Thanks!

**Comment by jsteemann** [comment]
AFAIK there is at least a golang implementation:
https://github.com/arangodb/go-velocypack

I am not sure about community implementations of VelocyPack. If you find one or start implementing one yourself, we are definitely interested in knowing and will link them here from our repository.
Thanks!

**Comment by graetzer** [comment]
https://github.com/arangodb/java-velocypack

**Comment by sandrokeil** [comment]
Experimental PHP extension https://github.com/martin-schilling/php-velocypack

**Comment by jsteemann** [comment]
Added these implementation to README.md of this repository.
