### ISSUE TITLE
Preventing attribute name sorting still possible?

### ISSUE THREAD

**Issue by martin-schilling** [arangodb/velocypack#30]
In the past there was a builder option called `sortAttributeNames` for this (which is still mentioned in the API.md):
```
Options options;
options.checkAttributeUniqueness = true;
options.sortAttributeNames = false;

Builder b(&options);

// now do something with Builder b
```
This feature was removed here: https://github.com/arangodb/velocypack/commit/985a1dcccad4ae0c876b1b7cb106971305725c08#diff-1f75eaa67fc2b9cdf6c00a241edcafcb

Is it still possible to prevent the builder from sorting the attribute names?

Thanks

**Comment by lamai93** [comment]
@martin-schilling having a unsorted index is does not add more functionality than having no index at all. Thus the compact object version can be used. You can use `void openObject(bool unindexed = false)` with `unindexed` set to true to generate compact objects.

**Comment by martin-schilling** [comment]
@lamai93 Thanks for your answer. I just tried your solution and it is exactly what I was looking for.
