### ISSUE TITLE
Index table for objects with single key/value pair

### ISSUE THREAD

**Issue by mpoeter** [arangodb/velocypack#45]
Having an index table for an object with a single key/value pair doesn't really make sense. In fact, this unit test from the java-velocypack implementation suggests that this superfluous index table can be omitted: https://github.com/arangodb/java-velocypack/blob/543f24419300fb12be6cc1b676089c924c0bd6f8/src/test/java/com/arangodb/velocypack/VPackSliceTest.java#L953-L960

However, when I try to create a document with the content `{0x0B, 7, 1, 65, 97, 40, 42}` via VelocyStream I get the following error: `VPackError error: given buffer length is unequal to actual length of Slice in buffer`.

What is the position on index tables for objects with only a single entry? I couldn't find anything in the documentation that mentions that an index table is optional in this case, but then the java implementation seems to be off.

**Comment by jsteemann** [comment]
@mpoeter: when using an object of type `0x0b`, it has to have an index table.
Precisely, all objects of types `0x0b` to `0x12` must have index tables.
In case no index table should be used, there is object type `0x14`.

**Comment by jsteemann** [comment]
The validation of objects of type `0x0b` will fail because the validator expects an index table at the end, but there is none.

**Comment by mpoeter** [comment]
Got it! But then the unittest in java-velocypack seems to be wrong, or at least misleading:
```java
// {"a":"b"}
final VPackSlice slice = new VPackSlice(
    new byte[] { 0x0b, 0x07, 0x01, 0x41, 0x61, 0x41, 0x62 });
```
This object is lacking an index table, but apparently the size (7) has been adapted accordingly. Not sure if the `VPackSlice` implementation is supposed to validate the data and recognize this. @hkernbach 

FWIW: I am not actually using java-velocypack. I am working on an Elixir implementation and simply used the java-velocypack unittests as reference.

**Comment by jsteemann** [comment]
No, `VPackSlice` will not do any sort of validation. Validation will only be done on demand.
There is an extra `VPackValidator` class that can be used for validation. 
I will ask my colleagues that maintain the java-velocypack part to look into this.
Thanks!

**Comment by rashtao** [comment]
I updated the cited java test with this vpack: `0x0b, 0x08, 0x01, 0x41, 0x61, 0x41, 0x62, 0x03`

https://github.com/arangodb/java-velocypack/commit/8fb5b25c6d18ef6904b8ef4d86f158680bf64866#diff-3db9e85532818437b3aed9c4484108bb
